### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Marsolvie** [djdiaguuu/bocikmcishard#1]
Mam taki problem, nie moge odpalic bota mam invaild token, invaild client id POMOCY!

**Comment by djdiaguuu** [comment]
Witaj,
Dziękujemy za kontakt z pomocą techniczną kammarsoft.

W pliku bot.js musisz zmienić swój token. Token utworzysz na stronie: https://discord.com/developers .

Mam nadzieję że pomogłem, Napisz w odpowiedzi czy mogę zamknąć zgłoszenie

Z poważaniem

Piotr Ż

Kammarsoft Support | Poziom 3

**Comment by Marsolvie** [comment]
tak problem rozwiązany dziękuję

**Comment by djdiaguuu** [comment]
Zgłoszenie zamknięte, Pomoc udana

**Comment by Marsolvie** [comment]
ee

**Comment by Marsolvie** [comment]
ja chcialem zamknac otworz to

**Comment by djdiaguuu** [comment]
ojojoj
juz otwieram ale masz 30 sekund na zamkniecie inaczej ja to zrobie

**Comment by Marsolvie** [comment]
zamykam

**Comment by Marsolvie** [comment]
hahahahahahahahahahahaha
